const completed=new Set(JSON.parse(localStorage.getItem('mc-completed')||'[]'));
const $=s=>document.querySelector(s);
const fields=[...new Set(TOPICS.map(t=>t[0]))];
$('#count').textContent=TOPICS.length;
fields.forEach(f=>$('#field').insertAdjacentHTML('beforeend',`<option>${f}</option>`));
function filtered(){const q=$('#search').value.toLowerCase(),f=$('#field').value,l=$('#level').value;return TOPICS.filter(t=>(f==='all'||t[0]===f)&&(l==='all'||t[1]===l)&&(!q||t.join(' ').toLowerCase().includes(q)));}
function renderChips(){const active=$('#field').value;$('#chips').innerHTML='<button class="chip '+(active==='all'?'active':'')+'" data-f="all">All</button>'+fields.map(f=>`<button class="chip ${active===f?'active':''}" data-f="${f}">${f}</button>`).join('');document.querySelectorAll('.chip').forEach(b=>b.onclick=()=>{$('#field').value=b.dataset.f;render();});}
function render(){renderChips();const xs=filtered();$('#grid').innerHTML=xs.length?xs.map((t,i)=>`<div class="card" data-i="${TOPICS.indexOf(t)}"><small>${t[0]} · ${t[1]}</small><h3>${t[2]}</h3><p>${t[3]}</p></div>`).join(''):'<p>No topics found.</p>';document.querySelectorAll('.card').forEach(c=>c.onclick=()=>openTopic(+c.dataset.i));}
function openTopic(i){const t=TOPICS[i];document.querySelectorAll('.topic-btn').forEach((b,n)=>b.classList.toggle('active',n===i));$('#detail').innerHTML=`<div class="detail"><div class="detail-top"><div><small>${t[0]} · ${t[1]}</small><h3>${t[2]}</h3><p>${t[3]}</p></div><button id="complete" class="complete ${completed.has(i)?'done':''}">${completed.has(i)?'✓ Completed':'Mark complete'}</button></div><div class="boxes"><div class="box"><h4>1 · Mathematics</h4><p>${t[4]}</p></div><div class="box"><h4>2 · How it works in code</h4><pre class="code">${esc(t[5])}</pre></div><div class="box"><h4>3 · Mathematics → Code</h4><p>Identify the mathematical objects, choose a representation, then implement the operation as an algorithm. Test boundary cases and numerical assumptions.</p><p class="muted"><b>Covered:</b> ${t[7]}</p></div><div class="box"><h4>4 · Difference</h4><div class="difference">${t[6]}</div></div></div></div>`;$('#complete').onclick=()=>{completed.has(i)?completed.delete(i):completed.add(i);localStorage.setItem('mc-completed',JSON.stringify([...completed]));openTopic(i);updateProgress();};}
function esc(s){return s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');}
function buildList(){ $('#list').innerHTML=TOPICS.map((t,i)=>`<button class="topic-btn" data-i="${i}">${t[2]}</button>`).join('');document.querySelectorAll('.topic-btn').forEach(b=>b.onclick=()=>openTopic(+b.dataset.i));}
function updateProgress(){const p=TOPICS.length?Math.round(completed.size/TOPICS.length*100):0;$('#pct').textContent=p+'%';$('#ring').style.background=`conic-gradient(var(--accent) ${p*3.6}deg,#e7e9ee 0deg)`;$('#pTitle').textContent=p===100?'Curriculum complete':'Keep going';$('#pText').textContent=`${completed.size} of ${TOPICS.length} mapped topics completed on this device.`;}
$('#search').oninput=render;$('#field').onchange=render;$('#level').onchange=render;
$('#run').onclick=()=>{const out=[];try{const fn=new Function('console', $('#editor').value);fn({log:(...a)=>out.push(a.map(x=>typeof x==='object'?JSON.stringify(x):String(x)).join(' '))});$('#output').textContent=out.join('\n')||'Code ran with no console output.';}catch(e){$('#output').textContent='Error: '+e.message;}};
$('#clear').onclick=()=>$('#output').textContent='';
$('#reset').onclick=()=>{if(confirm('Reset local progress?')){completed.clear();localStorage.removeItem('mc-completed');updateProgress();}};
render();buildList();openTopic(0);updateProgress();